language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  jobs:
    PYTEST_ADDOPTS="--strict --cov --cov-report=term-missing --cov-report=xml"

install:
  - travis_retry pip install -U tox-travis pip setuptools wheel
  - travis_retry pip install -r test-requirements.txt

script:
  - tox

stages:
  - test
  - name: deploy
    if: repo = dhatim/python-license-check AND tag IS present

jobs:
  include:
    - stage: deploy
      install: skip  # No need to install deps on deploy.
      script: skip  # No test on the deploy stage.
      after_success: true  # No need coverage
      python: "3.8"
      deploy:
        provider: pypi
        skip_existing: true
        user: Dev-Oss
        password:
          secure: AeTh3w8QeXQ6StzHlIbQcYZnr1qRjkQ4lBV0zup1t43dXxoRaXbQ7x2ZwcYpbM2h/lWeWssU2G6iY5ZW4a2t0+4go3PMPLSo2AC/sNJyVeuxvefkXTlWsL2YkTitpB1hhEzBVLMczNgf2OpLrmJIS/3hh1p3smiyj2xt1Jf7TaQ3bGneVFmlFrbOQTz5caoqjTRkhDWEa38pnSpbNIlgHIwhuDpVfUZn+Gh/UXmWdgiE1srpI1YLEMjpiFTe39Y36XvaJ/xszd/a929YgOalTZws+8iCzvI+/vSKdf1G+Phc4iVRbqwHAc4lfzbl42Yy81IMBrCMia/uum/lgkxZtcMJzyBwDXA0Rxtp1Ayh27bwI02tdJ3VQ8X8zvDJjATQhL2dRA5jqjNTco3SugM5rGcOvuLyjgROI9hQV0PSOXydqA/5kfLir5Y0cEpn5xW/RRVW5xgG9Pl6SzpS5vyd4/FB02wnp4pSxJM3v8WOUvMgKK4XjmMKKE8+IrY+avLLrhg3y3ziHdtjrnsVjo+fX+pdxymy85cNDVVH+AfBhG+Hnf2svxA4HnKzN9QaTGLB7EjU8TYCa1eJ8djSbEF9MStw2+b3cUG65jvWjDt/sPwzmcsrAob4rcy5pIBQbbtAa48lqighjjpM8EkDepLJaduDYUIbf3K+dKNjsKBXAo4=
        on:
          tags: true
          repo: dhatim/python-license-check

after_success:
  - travis_retry pip install codecov
  - travis_retry codecov
